name: "CI workflow"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: "Run unit test"
    defaults:
      run:
        shell: bash
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Print current path"
        run: pwd

      - name: "Make script executable"
        run: chmod +x ./shell/test.sh

      - name: "Run test script"
        run: ./shell/test.sh
